FROM php:7.4-apache

WORKDIR /var/www/html

# Install dependencies
RUN apt-get update && apt-get install -y \
        gnupg \
        git \
        curl \
        zip \
        unzip

#PHP Config
RUN docker-php-ext-install pdo_mysql
COPY conf/php/php.ini /usr/local/etc/php/conf.d/app.ini

#Install composer
ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /tmp
ENV COMPOSER_VERSION 1.10.7
RUN set -eux; \
  curl --silent --fail --location --retry 3 --output /tmp/installer.php --url https://raw.githubusercontent.com/composer/getcomposer.org/cb19f2aa3aeaa2006c0cd69a7ef011eb31463067/web/installer; \
  php /tmp/installer.php --no-ansi --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION}; \
  composer --ansi --version --no-interaction; \
  rm -f /tmp/installer.php; \
  find /tmp -type d -exec chmod -v 1777 {} +

#Apache config
COPY conf/apache/vhost.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

RUN echo "alias ll='ls -lah'" >> /root/.bashrc
