FROM php:7.4-apache

WORKDIR /var/www/html

# Install dependencies
RUN apt-get update && apt-get install -y \
        gnupg \
        git \
        zip \
        unzip \
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
        apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#PHP Config
RUN docker-php-ext-install pdo_mysql
COPY conf/php/php.ini /usr/local/etc/php/conf.d/app.ini

#Apache config
COPY conf/apache/vhost.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

RUN echo "alias ll='ls -lah'" >> /root/.bashrc
