name: Continuous Deployement
on:
  push:
    branches:
      - master

jobs:
  deploy_production:
    name: Deployement in production
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Copy repository contents via SCP
        uses : appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          KEY_PATH: ${{ secrets.KEY_PATH }}
        with:
          source: "."
          target: "/var/www/web2-2021-project"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          KEY_PATH: ${{ secrets.KEY_PATH }}
          debug: true
          script: |
            ls